#!/usr/bin/env sh

export WORKER_CONNECTIONS=${WORKER_CONNECTIONS:-726}
export PROXY_READ_TIMEOUT=${PROXY_READ_TIMEOUT:-60}

export REPLACE_VARS='$PORT:$APP_SERVER:$WORKER_CONNECTIONS:$PROXY_READ_TIMEOUT:$HSTS'

envsubst "$REPLACE_VARS" < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

exec nginx -g 'daemon off;'
